Vagrant.configure("2") do |config|
  config.vm.box = "g0v"
  config.vm.provision :shell, :inline => <<EOF
  echo HI
EOF

  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "./cookbooks"
    chef.roles_path = "./roles"
    chef.data_bags_path = "./data_bags"
    chef.add_recipe 'git'
    chef.add_recipe 'nodejs'
    chef.add_recipe 'postgresql'
    chef.add_recipe 'postgresql::server'
    chef.add_recipe "liquid-feedback"

#    chef.add_recipe 'postfix'
#    chef.add_recipe 'postfix::sasl_auth'
#    chef.add_recipe 'sesgateway'
 
    # You may also specify custom JSON attributes:
    chef.json.merge!(JSON.parse(File.read("./dna.json")))
  end
end
